# Generated by Django 5.2.1 on 2025-06-03 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedDataCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(help_text='JSON serialized ParsedRequirementData')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Parsed Data Cache',
                'verbose_name_plural': 'Parsed Data Caches',
            },
        ),
    ]
