# Generated by Django 5.2.2 on 2025-06-10 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_provider', models.CharField(default='openai', max_length=32)),
                ('openai_model', models.CharField(blank=True, max_length=64, null=True)),
                ('gemini_model', models.CharField(blank=True, max_length=64, null=True)),
                ('openai_api_key', models.CharField(blank=True, max_length=128, null=True)),
                ('gemini_api_key', models.CharField(blank=True, max_length=128, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
